language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
before_install:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
before_script:
  - git clone --branch=master --depth=1 --quiet git://github.com/WoltLab/WCF.git WCF
script:
  - find . -type f -name '*.php' -not -path "./WCF/*" |xargs -I file php -l file
  - phpcs -p --extensions=php --standard="`pwd`/WCF/CodeSniff/WCF" . --ignore="/WCF/*"

notifications:
  email: false
  